version: '3'
services:
  database:
    build: ./database
    ports:
      - "3306:3306"
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DBHOST=database
